const Config = {
    
    blipsCount: 110,
    banMessage: "Contactez le staff si vous pensez que le ban est une erreur",
    
    weaponList: ["WEAPON_KNIFE","WEAPON_KNUCKLE","WEAPON_HAMMER","WEAPON_NIGHTSTICK","WEAPON_BAT","WEAPON_GOLFCLUB","WEAPON_CROWBAR","WEAPON_BOTTLE","WEAPON_DAGGER","WEAPON_HATCHET","WEAPON_MACHETE","WEAPON_FLASHLIGHT" ,"WEAPON_SWITCHBLADE","WEAPON_PROXMINE","WEAPON_BZGAS","WEAPON_SMOKEGRENADE","WEAPON_MOLOTOV","WEAPON_FIREEXTINGUISHER","WEAPON_PETROLCAN","WEAPON_SNOWBALL","WEAPON_FLARE","WEAPON_BALL","WEAPON_POOLCUE","WEAPON_REVOLVER" ,"WEAPON_PIPEWRENCH","WEAPON_PISTOL","WEAPON_PISTOL_MK2","WEAPON_COMBATPISTOL","WEAPON_APPISTOL","WEAPON_PISTOL50","WEAPON_SNSPISTOL","WEAPON_HEAVYPISTOL","WEAPON_VINTAGEPISTOL","WEAPON_STUNGUN","WEAPON_FLAREGUN","WEAPON_MARKSMANPISTOL","WEAPON_MICROSMG","WEAPON_MINISMG","WEAPON_SMG","WEAPON_SMG_MK2","WEAPON_ASSAULTSMG","WEAPON_MG","WEAPON_COMBATMG" ,"WEAPON_COMBATMG_MK2","WEAPON_COMBATPDW","WEAPON_GUSENBERG","WEAPON_MACHINEPISTOL","WEAPON_ASSAULTRIFLE","WEAPON_ASSAULTRIFLE_MK2","WEAPON_CARBINERIFLE","WEAPON_CARBINERIFLE_MK2","WEAPON_ADVANCEDRIFLE","WEAPON_SPECIALCARBINE","WEAPON_BULLPUPRIFLE","WEAPON_COMPACTRIFLE","WEAPON_PUMPSHOTGUN" ,"WEAPON_SWEEPERSHOTGUN","WEAPON_SAWNOFFSHOTGUN","WEAPON_BULLPUPSHOTGUN","WEAPON_ASSAULTSHOTGUN","WEAPON_MUSKET","WEAPON_HEAVYSHOTGUN","WEAPON_DBSHOTGUN","WEAPON_SNIPERRIFLE","WEAPON_HEAVYSNIPER","WEAPON_HEAVYSNIPER_MK2","WEAPON_MARKSMANRIFLE","WEAPON_GRENADELAUNCHER","WEAPON_GRENADELAUNCHER_SMOKE","WEAPON_RPG","WEAPON_MINIGUN","WEAPON_FIREWORK","WEAPON_RAILGUN","WEAPON_HOMINGLAUNCHER","WEAPON_GRENADE","WEAPON_STICKYBOMB","WEAPON_COMPACTLAUNCHER","WEAPON_SNSPISTOL_MK2","WEAPON_REVOLVER_MK2","WEAPON_DOUBLEACTION","WEAPON_BULLPUPRIFLE_MK2","WEAPON_SPECIALCARBINE_MK2","WEAPON_PUMPSHOTGUN_MK2","WEAPON_MARKSMANRIFLE_MK2","WEAPON_DIGISCANNER","WEAPON_RAYPISTOL","WEAPON_RAYCARBINE","WEAPON_RAYMINIGUN", "WEAPON_AUTOSHOTGUN", "WEAPON_PIPEBOMB", "WEAPON_BATTLEAXE", "WEAPON_WRENCH", "WEAPON_STONE_HATCHET"],
    
    realResources: [
        "monitor",
        "baseevents",
        "loadingscreen",
        "gsan_ipl",
        "rGM",
        "RAC",
        "gsan_ui"
    ],

    ClientWeaponDamage: {
        "453432689": 26.0, // WEAPON_PISTOL
        "1593441988": 27.0, // WEAPON_COMBATPISTOL
        "584646201": 25.0, // WEAPON_APPISTOL
        "-1716589765": 51.0, // WEAPON_PISTOL50
        "324215364": 21.0, // WEAPON_MICROSMG
        "736523883": 22.0, // WEAPON_SMG
        "-270015777": 23.0, // WEAPON_ASSAULTSMG
        "-1074790547": 30.0, // WEAPON_ASSAULTRIFLE
        "-2084633992": 32.0, // WEAPON_CARBINERIFLE
        "-1357824103": 34.0, // WEAPON_ADVANCEDRIFLE
        "-1660422300": 40.0, // WEAPON_MG
        "2144741730": 45.0, // WEAPON_COMBATMG
        "487013001": 29.0, // WEAPON_PUMPSHOTGUN
        "2017895192": 40.0, // WEAPON_SAWNOFFSHOTGUN
        "-494615257": 32.0, // WEAPON_ASSAULTSHOTGUN
        "-1654528753": 14.0, // WEAPON_BULLPUPSHOTGUN
        "100416529": 101.0, // WEAPON_SNIPERRIFLE
        "205991906": 214.0, // WEAPON_HEAVYSNIPER
        "1119849093": 30.0, // WEAPON_MINIGUN
        "-1076751822": 28.0, // WEAPON_SNSPISTOL
        "1627465347": 34.0, // WEAPON_GUSENBERG
        "-1063057011": 32.0, // WEAPON_SPECIALCARBINE
        "-771403250": 40.0, // WEAPON_HEAVYPISTOL
        "2132975508": 32.0, // WEAPON_BULLPUPRIFLE
        "137902532": 34.0, // WEAPON_VINTAGEPISTOL
        "-1466123874": 165.0, // WEAPON_MUSKET
        "984333226": 117.0, // WEAPON_HEAVYSHOTGUN
        "-952879014": 65.0, // WEAPON_MARKSMANRIFLE
        "1198879012": 10.0, // WEAPON_FLAREGUN
        "171789620": 26.0, // WEAPON_COMBATPDW
        "-598887786": 220.0, // WEAPON_MARKSMANPISTOL
        "-619010992": 27.0, // WEAPON_MACHINEPISTOL
        "-275439685": 30.0, // WEAPON_DBSHOTGUN
        "1649403952": 34.0, // WEAPON_COMPACTRIFLE
        "317205821": 27.0, // WEAPON_AUTOSHOTGUN
        "-1121678507": 22.0, // WEAPON_MINISMG
        "-2009644972": 30.0, // WEAPON_SNSPISTOL_MK2
        "-1768145561": 32.5, // WEAPON_SPECIALCARBINE_MK2
        "-2066285827": 33.0, // WEAPON_BULLPUPRIFLE_MK2
        "1432025498": 32.0, // WEAPON_PUMPSHOTGUN_MK2
        "1785463520": 75.0, // WEAPON_MARKSMANRIFLE_MK2
        "961495388": 40.0, // WEAPON_ASSAULTRIFLE_MK2
        "-86904375": 33.0, // WEAPON_CARBINERIFLE_MK2
        "-608341376": 47.0, // WEAPON_COMBATMG_MK2
        "177293209": 230.0, // WEAPON_HEAVYSNIPER_MK2
        "-1075685676": 32.0, // WEAPON_PISTOL_MK2
        "2024373456": 25.0 // WEAPON_SMG_MK2
    },

    blacklistedPeds: [
        "s_m_y_swat_01",
        "a_m_o_acult_01",
        "ig_wade",
        "s_m_y_hwaycop_01",
        "A_M_Y_ACult_01",
        's_m_m_movalien_01',
        's_m_m_movallien_01',
        'u_m_y_babyd',
        'CS_Orleans',
        'A_M_Y_ACult_01',
        'S_M_M_MovSpace_01',
        'U_M_Y_Zombie_01',
        's_m_y_blackops_01',
        'a_f_y_topless_01',
        'a_c_boar',
        'a_c_cat_01',
        'a_c_chickenhawk',
        'a_c_chimp',
        's_f_y_hooker_03',
        'a_c_chop',
        'a_c_cormorant',
        'a_c_cow',
        'a_c_coyote',
        'a_c_crow',
        'a_c_dolphin',
        'a_c_fish',
        's_f_y_hooker_01',
        'a_c_hen',
        'a_c_humpback',
        'a_c_husky',
        'a_c_killerwhale',
        'a_c_mtlion',
        'a_c_pigeon',
        'a_c_poodle',
        'a_c_pug',
        'a_c_rabbit_01',
        'a_c_rat',
        'a_c_retriever',
        'a_c_rhesus',
        'a_c_rottweiler',
        'a_c_sharkhammer',
        'a_c_sharktiger',
        'a_c_shepherd',
        'a_c_stingray',
        'a_c_westy',
        'CS_Orleans',
        'a_m_m_fatlatin_01',
        'mp_m_g_vagfun_01',
        'csb_bride',
        's_m_m_movspace_01',
        'a_c_sharktiger',
        'a_c_deer',
        'a_c_humpback'
    ],

    PickupList: ["PICKUP_AMMO_BULLET_MP","PICKUP_AMMO_FIREWORK","PICKUP_AMMO_FLAREGUN","PICKUP_AMMO_GRENADELAUNCHER","PICKUP_AMMO_GRENADELAUNCHER_MP","PICKUP_AMMO_HOMINGLAUNCHER","PICKUP_AMMO_MG","PICKUP_AMMO_MINIGUN","PICKUP_AMMO_MISSILE_MP","PICKUP_AMMO_PISTOL","PICKUP_AMMO_RIFLE","PICKUP_AMMO_RPG","PICKUP_AMMO_SHOTGUN","PICKUP_AMMO_SMG","PICKUP_AMMO_SNIPER","PICKUP_ARMOUR_STANDARD","PICKUP_CAMERA","PICKUP_CUSTOM_SCRIPT","PICKUP_GANG_ATTACK_MONEY","PICKUP_HEALTH_SNACK","PICKUP_HEALTH_STANDARD","PICKUP_MONEY_CASE","PICKUP_MONEY_DEP_BAG","PICKUP_MONEY_MED_BAG","PICKUP_MONEY_PAPER_BAG","PICKUP_MONEY_PURSE","PICKUP_MONEY_SECURITY_CASE","PICKUP_MONEY_VARIABLE","PICKUP_MONEY_WALLET","PICKUP_PARACHUTE","PICKUP_PORTABLE_CRATE_FIXED_INCAR","PICKUP_PORTABLE_CRATE_UNFIXED","PICKUP_PORTABLE_CRATE_UNFIXED_INCAR","PICKUP_PORTABLE_CRATE_UNFIXED_INCAR_SMALL","PICKUP_PORTABLE_CRATE_UNFIXED_LOW_GLOW","PICKUP_PORTABLE_DLC_VEHICLE_PACKAGE","PICKUP_PORTABLE_PACKAGE","PICKUP_SUBMARINE","PICKUP_VEHICLE_ARMOUR_STANDARD","PICKUP_VEHICLE_CUSTOM_SCRIPT","PICKUP_VEHICLE_CUSTOM_SCRIPT_LOW_GLOW","PICKUP_VEHICLE_HEALTH_STANDARD","PICKUP_VEHICLE_HEALTH_STANDARD_LOW_GLOW","PICKUP_VEHICLE_MONEY_VARIABLE","PICKUP_VEHICLE_WEAPON_APPISTOL","PICKUP_VEHICLE_WEAPON_ASSAULTSMG","PICKUP_VEHICLE_WEAPON_COMBATPISTOL","PICKUP_VEHICLE_WEAPON_GRENADE","PICKUP_VEHICLE_WEAPON_MICROSMG","PICKUP_VEHICLE_WEAPON_MOLOTOV","PICKUP_VEHICLE_WEAPON_PISTOL","PICKUP_VEHICLE_WEAPON_PISTOL50","PICKUP_VEHICLE_WEAPON_SAWNOFF","PICKUP_VEHICLE_WEAPON_SMG","PICKUP_VEHICLE_WEAPON_SMOKEGRENADE","PICKUP_VEHICLE_WEAPON_STICKYBOMB","PICKUP_WEAPON_ADVANCEDRIFLE","PICKUP_WEAPON_APPISTOL","PICKUP_WEAPON_ASSAULTRIFLE","PICKUP_WEAPON_ASSAULTSHOTGUN","PICKUP_WEAPON_ASSAULTSMG","PICKUP_WEAPON_AUTOSHOTGUN","PICKUP_WEAPON_BAT","PICKUP_WEAPON_BATTLEAXE","PICKUP_WEAPON_BOTTLE","PICKUP_WEAPON_BULLPUPRIFLE","PICKUP_WEAPON_BULLPUPSHOTGUN","PICKUP_WEAPON_CARBINERIFLE","PICKUP_WEAPON_COMBATMG","PICKUP_WEAPON_COMBATPDW","PICKUP_WEAPON_COMBATPISTOL","PICKUP_WEAPON_COMPACTLAUNCHER","PICKUP_WEAPON_COMPACTRIFLE","PICKUP_WEAPON_CROWBAR","PICKUP_WEAPON_DAGGER","PICKUP_WEAPON_DBSHOTGUN","PICKUP_WEAPON_FIREWORK","PICKUP_WEAPON_FLAREGUN","PICKUP_WEAPON_FLASHLIGHT","PICKUP_WEAPON_GRENADE","PICKUP_WEAPON_GRENADELAUNCHER","PICKUP_WEAPON_GUSENBERG","PICKUP_WEAPON_GOLFCLUB","PICKUP_WEAPON_HAMMER","PICKUP_WEAPON_HATCHET","PICKUP_WEAPON_HEAVYPISTOL","PICKUP_WEAPON_HEAVYSHOTGUN","PICKUP_WEAPON_HEAVYSNIPER","PICKUP_WEAPON_HOMINGLAUNCHER","PICKUP_WEAPON_KNIFE","PICKUP_WEAPON_KNUCKLE","PICKUP_WEAPON_MACHETE","PICKUP_WEAPON_MACHINEPISTOL","PICKUP_WEAPON_MARKSMANPISTOL","PICKUP_WEAPON_MARKSMANRIFLE","PICKUP_WEAPON_MG","PICKUP_WEAPON_MICROSMG","PICKUP_WEAPON_MINIGUN","PICKUP_WEAPON_MINISMG","PICKUP_WEAPON_MOLOTOV","PICKUP_WEAPON_MUSKET","PICKUP_WEAPON_NIGHTSTICK","PICKUP_WEAPON_PETROLCAN","PICKUP_WEAPON_PIPEBOMB","PICKUP_WEAPON_PISTOL","PICKUP_WEAPON_PISTOL50","PICKUP_WEAPON_POOLCUE","PICKUP_WEAPON_PROXMINE","PICKUP_WEAPON_PUMPSHOTGUN","PICKUP_WEAPON_RAILGUN","PICKUP_WEAPON_REVOLVER","PICKUP_WEAPON_RPG","PICKUP_WEAPON_SAWNOFFSHOTGUN","PICKUP_WEAPON_SMG","PICKUP_WEAPON_SMOKEGRENADE","PICKUP_WEAPON_SNIPERRIFLE","PICKUP_WEAPON_SNSPISTOL","PICKUP_WEAPON_SPECIALCARBINE","PICKUP_WEAPON_STICKYBOMB","PICKUP_WEAPON_STUNGUN","PICKUP_WEAPON_SWITCHBLADE","PICKUP_WEAPON_VINTAGEPISTOL","PICKUP_WEAPON_WRENCH", "PICKUP_WEAPON_RAYCARBINE"],
}